<?php
   
    function basic_page_theme($existing,$theme,$type,$path){
        return array(
            'information_page'=>array(
                'variables'=>array(
                    'items'=>[],
                    'title'=>''
                )
            )
                
        );
    }

/*<?php
   function basic_page_theme($existing,$theme,$type,$path){
     return array(
        'basic_page'=>array(
            'variables'=>array(
                'es'=>[],
                'title'=>''
            )
        )
            
    );
}
*/